# Generated by Django 5.2.1 on 2025-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('team', models.CharField(db_index=True, max_length=50)),
                ('player', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('total_runs', models.PositiveIntegerField()),
                ('total_fours', models.PositiveSmallIntegerField()),
                ('total_sixes', models.PositiveSmallIntegerField()),
                ('total_wickets', models.PositiveSmallIntegerField()),
                ('total_dots', models.PositiveIntegerField()),
                ('total_50s', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-year', 'team'],
                'indexes': [models.Index(fields=['year', 'team'], name='stats_playe_year_d69fdb_idx'), models.Index(fields=['player'], name='stats_playe_player_a940e9_idx')],
            },
        ),
    ]
