# Generated by Django 5.2.1 on 2025-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_playerstatarchive_alter_playerstat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('team', models.CharField(db_index=True, max_length=64)),
                ('player', models.CharField(db_index=True, max_length=128)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-keeper', 'Wicket-keeper')], max_length=32)),
                ('total_runs', models.PositiveIntegerField()),
                ('total_fours', models.PositiveIntegerField()),
                ('total_sixes', models.PositiveIntegerField()),
                ('total_wickets', models.PositiveIntegerField()),
                ('total_dots', models.PositiveIntegerField()),
                ('total_fifties', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-year', 'team', 'player'],
            },
        ),
        migrations.DeleteModel(
            name='PlayerStat',
        ),
        migrations.DeleteModel(
            name='PlayerStatArchive',
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['year', 'team'], name='stats_playe_year_4d0f7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonstat',
            unique_together={('year', 'team', 'player')},
        ),
    ]
